remote_theme: raviriley/agency-jekyll-theme
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: FriquiFund
#TODO: email: info@friquifund.org
description: Helping geeks grow
#TODO url : "https://alsak0de.github.io/ff" 
baseurl: /
show_downloads: false
author: FriquiFund


logo:
  path: /img/FriquiFund_transparent_font58_res72dp_white_half_wide.png
  height: 40
icon:
  path: /img/icon.png

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: G-CDEB4MQ0QJ # Google Analytics tracking code (Andreu Mayo account)


#collections:
#  portfolio:

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id"

exclude:
  - test
