google2:
  installed:
    #client_id: << GOOGLE_CLIENT_ID >>
    #project_id: << GOOGLE_PROJECT_ID >>
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://oauth2.googleapis.com/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    #client_secret: << GOOGLE_CLIENT_SECRET >>
    redirect_uris: ["http://localhost"]
google:
  type: service_account
  project_id: << GOOGLE_PROJECT_ID >>
  private_key_id: << GOOGLE_PRIVATE_KEY_ID >>
  private_key: << GOOGLE_PRIVATE_KEY >>
  client_email: << GOOGLE_CLIENT_EMAIL >>
  client_id: << GOOGLE_CLIENT_ID >>
  auth_uri: "https://accounts.google.com/o/oauth2/auth"
  token_uri: "https://oauth2.googleapis.com/token"
  auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
  client_x509_cert_url: << GOOGLE_CLIENT_X509_CERT >>
  universe_domain: "googleapis.com"

linkedin:
  user: << LINKEDIN_USER >>
  password: << LINKEDIN_PASSWORD >>

nubela_api_key: << NUBELA_API_KEY >>
serapi_api_key: << SERAPI_API_KEY >>