project_paths:
  website_repo: !path [<< WEBSITE_REPO >>]

csv_web: !path ["{datasets.project_paths.website_repo}", _data, team.csv]
image_folder: !path ["{datasets.project_paths.website_repo}", pics]
spreadsheet_members: << GOOGLE_MEMBERS_SPREADSHEET >>
spreadsheet_api: << GOOGLE_PROXY_API_SPREADSHEET >>
spreadsheet_team: << GOOGLE_TEAM_SPREADSHEET >>

preprocess:
  csv_web:
    rename:
      LinkedIn: linkedin
      Name: name
      picfile: picfile
    recast:
      linkedin: str