update_frequency_months: 10
max_profiles_update: 5

leadership_members:
  - "Hugo Zaragoza Ballester"
  - "Nathalie Vento"
  - "Pau-Agulló"
  - "Oleguer Sagarra"
  - "Xavier Amatriain"
  - "Anna Saumell Mendiola"
  - "David Bofill"
  - "Elisenda Bou"
  - "Andreu Mayo"
  - "Winslow Robertson"
  - "Léonce ANO"
  - "Magda Grucza"